version: '3'
services:
  hello-client:
    build: hello-world-distributed/client
    ports:
      - 8090:8080
  hello-service:
    build: hello-world-distributed/service
    ports:
      - 8080
  hello-translation-service:
    build: hello-world-distributed/translation
    ports:
      - 8080